### ISSUE TITLE
Compiler outputs error messages even after offending code is removed

### ISSUE THREAD

**Issue by shawnhwei** [aMarCruz/pugjs-brunch#1] opened 2016-11-16 09:55 UTC
This happens to me when using brunch watch.

For example, if you have some invalid code:
```
| test
  | test
```
```
16 Nov 17:48:36 - error: Compiling of static/assets/test.pug failed. static/assets/test.pug:2:1
    1| | test
  > 2|   | test
-------^

unexpected token "indent"
```
Then make it valid and save:
```
| test
| test
```
```
16 Nov 17:48:36 - error: Compiling of static/assets/test.pug failed. static/assets/test.pug:2:1
    1| | test
  > 2|   | test
-------^

unexpected token "indent"
16 Nov 17:48:38 - error: Compiling of static/assets/test.pug failed. static/assets/test.pug:2:1
    1| | test
  > 2|   | test
-------^

unexpected token "indent"
```
The indentation error is still being output after every subsequent save. I can delete everything in the file and it still outputs that same error.

**Comment by aMarCruz** [comment] 2016-11-16 10:16
@shawnhwei looks like an issue with chache. Strange things happen when Brunch+watch are used :)

I'm not in my dev machine right now, tomorrow I'll do some tests.

Thanks for your feedback.

**Comment by aMarCruz** [comment] 2016-11-18 19:05
@shawnhwei confirmed: the bug comes from Brunch serving the included files from its caché, I don't have a fix yet. I'll working on this asap.

**Comment by aMarCruz** [comment] 2016-12-29 20:34
@shawnhwei , v2.8.6 is out and I can't reproduce the problem now, so I'm closing this issue.

btw, this is the dependencies of my current project, a SPA with ~150 pug files, with no more than 4 levels nested (mainly includes with and without underscore prefix):
```js
  "dependencies": {
    "dropzone": "^4.3.0",
    "easyrouter": "^0.1.3",
    "jquery": "^2.2.4",
    "js-cookie": "^2.1.3",
    "json-brunch": "^1.5.4",
    "pusher-js": "^4.0.0",
    "store2": "^2.3.2"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "jscc-brunch": "^2.8.2",
    "brunch": "^2.9.1",
    "bublejs-brunch": "^2.8.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.6.1",
    "javascript-brunch": "^2.0.0",
    "less-brunch": "^2.7.1",
    "pugjs-brunch": "^2.8.6",
    "uglify-js-brunch": "^2.0.1"
  },
```

and (partial) brunch-config.js
```js
  // custom server port
  server: {
    run: true,
    port: 8080
  },
  watcher: {
    usePolling: true
  },
  plugins: {
    jscc: {
      values: values,
      pattern: /\.(?:js|pug)$/,
      sourceMapFor: /\.(?:js|pug)$/
    },
    buble: {
      objectAssign: 'assign'
    },
    pug: {
      globals: ['App'],
      sourceMap: true,
      compileDebug: false
    }
  },
```

working in Linux mint 18

**Closed as completed by aMarCruz** 2016-12-29 20:34 UTC
Labels: bug
